### ISSUE TITLE
Automate Issues

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#1112]
## Summary

Automate the GH Project boards and other things using workflows/actions.

The goal here is to automate most of the process for adding tasks to the GitHub Projects boards. The logic should follow something like:

### Milestones

- [x] When a GItHub Milestone is created:
  - create a new GitHub Project with the same name, using a project template copying our current format.

- [x] When a GitHub Milestone has its name changed:
  - rename the GitHub Project with the same name as the Milestone to the Milestone's new name. 

- [x] When a GitHub Milestone closes:
  - close the GitHub Project of the same name.

### Issues

- [x] When a GitHub Milestone is added to an *open* issue:
  - add the issue to the GH Project of the same name as the Milestone, in the 'backlog' column.

- [ ] When a PR links to close an *open* issue:
  - if the issue is in a GH Project
    - move the issue to the 'in progress' column

- [ ] When an issue is closed:
  - if the issue is in a GH Project
    - if the issue was closed via a merged PR
      - move the issue to the 'done' column
    - else
      - remove the issue from the GH Project

### Pull Requests

- [x] When a GitHub Milestone is added to an *open* PR (develop repo):
  - if the PR has "WIP" in the title
    - add the PR to the GH Project of the same name as the Milestone, in the 'in progress' column
  - else
    - add the PR to the GH Project of the same name as the Milestone, in the 'in review' column

- [ ] When a contributor updates the title of a PR (develop repo):
  - if the PR is in a GH Project
    - if the PR has "WIP" in the title
      - move the PR to the 'in progress' column
    - else
      - move the PR to the 'in review' column

- [ ] When a PR is merged (develop repo) (this should already happen by default):
  - if the PR is in a GH Project
    - move the PR to the 'done' column

- [ ] When a PR is closed (develop repo):
  - if the PR is in a GH Project
    - remove the PR from the GH Project

### Labels

- [ ] When the "Blocked" label is added to an issue/PR:
  - if the issue/PR is in a GH project
    - move the issue/PR to the "Blocked" column

- [ ] When the "Blocked" label is removed from an issue/PR:
  - if the issue/PR is in a GH project
    - If issue
      - move the issue to the "Backlog" column
    - If PR
      - move the PR to the "In Progress" column

### Assigning

- [x] When a PR links to close an *open* issue:
  - assign the issue to the PR owner if they aren't already assigned

- [x] When a contributor says "assign me" (not case-sensitive) in a comment on an issue: 
  - if the issue has no assignees
    - assign the contributor to the issue

- [x] When a contributor says "unassign me" (not case-sensitive) in a comment on an issue:
  - if the issue is assigned to the contributor
    - unassign the contributor from the issue

- [ ] ~~When an *open* issue has been assigned for 2 months (and still open):~~
  - ~~unassign the contributor from the issue~~

**Comment by stilnat** [comment]
It seems there's a few issues with github's new projects and the actions of github-project-automation-plus@v0.8.3.
Some people me included, experimented this issue of not finding a project with actions from this repository :
https://github.com/alex-page/github-project-automation-plus/issues/81

**Comment by cosmiccoincidence** [comment]
Interesting. Might explain my issues with getting it working on this repo as well.
I'm pretty new to GH actions but if this one doesn't work for us, can't we find another one?

**Comment by stilnat** [comment]
- [ ] > when a GItHub Milestone is created

      > ceate a new GitHub Project with the same name, using a project template copying our current format.

- [ ] > when a GitHub Milestone has its name changed

      > rename the GitHub Project with the same name as the Milestone to the Milestone's new name. 

- [ ] > when a GitHub Milestone closes

      > close the GitHub Project of the same name



- [ ] > when a GitHub Milestone is added to an *open* issue

      > add the issue to the GH Project of the same name as the Milestone, in the 'backlog' column

- [ ] > when a PR links to close an *open* issue

      > if the issue is in a GH Project
            > move the issue to the 'in progress' column

- [ ] > when an issue is closed

      > if the issue is in a GH Project
            > if the issue was closed via a merged PR
                  > move the issue to the 'done' column
            > else
                  > remove the issue from the GH Project

- [ ] (When blocked label is added/removed move it from to the blocked column)

- [ ] > when a GitHub Milestone is added to an *open* PR (develop repo)

      > if the PR has "WIP" in the title
            > add the PR to the GH Project of the same name as the Milestone, in the 'in progress' column
      > else
            > add the PR to the GH Project of the same name as the Milestone, in the 'in review' column

- [ ] > when a contributor updates the title of a PR (develop repo)

      > if the PR is in a GH Project
            > if the PR has "WIP" in the title
                  > move the PR to the 'in progress' column
            > else
                  > move the PR to the 'in review' column

- [ ] > when a PR is merged (develop repo) (this should already happen by default)

      > if the PR is in a GH Project
            > move the PR to the 'done' column

- [ ] > when a PR is closed (develop repo)

      > if the PR is in a GH Project
            > remove the PR from the GH Project

**Comment by stilnat** [comment]
So it turns out that github introduced a new kind of "project", the old ones are called "classic projects", and most actions on the github marketplace don't work with those one. [One of the very few working](https://github.com/marketplace/actions/add-to-github-projects) is very poor in features.  

If you know of an action that could perform those tasks above or even a subset of it, we'll take it.
If you know how to write actions using the new Github API even better.

**Comment by Ryan089** [comment]
> When an open issue has been assigned for 2 months (and still open): unassign the contributor from the issue

I disagree with this particular item, and won't attempt to implement it. Some things take time, and the contributor may be detailing their progress every day, so it would be inappropriate to automatically remove them. As an example, this rule could unassign me from this issue, despite several merged PR's tackling discrete tasks. Unassigning someone due to inactivity should remain a Centcom judgment call.

**Comment by Ryan089** [comment]
Assign me
