### ISSUE TITLE
Begin Migrating Assets to GitHub

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#171]
### Summary

Begin the slow process of migrating the art assets from the OneDrive account to the GitHub project.

### Goal 

Assets will slowly move from the onedrive to this repo via pull requests. The process of this will be tracked in this issue and on the asset trello boards via labels (add details on the labels later...). Once the asset is accepted into the repo, it will no longer be maintained on the OneDrive
(This might get moved to a GitHub Project at some point, not sure yet.)

For now, mostly only concentrating on 'high priority' assets that could be useful for adding more technical content.

Assets:
- [X] tables (#143)
- [x] additional floors (tile/object)
- [x] girders
- [x] plenums (useful for #125)
- [x] pipes
- [X] double airlocks (useful for #128)
- [x] fire alarm & fire warning light
- [x] light fixtures & light bulbs (useful for #164)
- [x] APC & light switch
- [x] fire extinguisher
- [x] posters & textures
- [x] wires
- [x] potted plants
- [x] hydroponics tray, some plants, food, seeds
- [x] seats (chair, stool, comfy chair)
- [x] janitors cart, & related items
- [x] crates
- [x] file cabinet, papers, & pens
- [x] fridge & food/drinks
- [x] microwave, salt, pepper, & foods
- [x] solar panels
- [x] MegaSeed & seeds
- [x] Booze-o-Mat & booze
- [x] Getmore & snacks
- [x] Robust Softdrinks & soda
- [x] cig machine, cigs, & lighter
- [x] Youtool & tools
- [x] Dinnerware & silverware
- [x] tank dispenser & gas tanks
- [x] table lamps
- [X] common materials (steel, plasteel, plasma, glass, reinforced glass)
- [X] toolbox & common tools (flashlight, radio, wrench, crowbar, screwdriver, wirecutters, welder, multitool, t-ray scanner)
- [x] IDs
- [ ] PDAs
- [ ] clothing

### Document

(I'll link specific issues and trello cards to the list above as time goes on.)

### Other

You will need the assets files to add them to the project obviously, so if you want to help with these but don't have the files, let me know.
